In [1]:
import tensorflow as tf
import numpy as np

from collections import namedtuple
import time

In [2]:
## converting chars to integers
with open('anna.txt','r') as f:
    text= f.read()

vocab = set(text)

In [3]:
print(vocab)
print(len(vocab))
## we get all the unique terms used

{')', 'K', 'T', '_', 'L', 'B', '`', 'o', 'X', 'l', 'P', '5', '(', ';', 'v', '8', 'n', 'C', 'h', 'e', '0', 'x', 'Y', ':', '3', '4', 'V', '"', '*', 'F', 'j', '\n', '!', 'R', 'Q', 'S', '/', '2', '%', '?', 'm', '.', 'y', 'f', 'q', 'G', 'Z', '6', 'i', 'D', 'u', 'I', 'z', 'p', 'r', '-', 'g', 's', 'b', 'W', '7', 'U', 'O', '9', '@', '&', 't', 'w', 'c', 'M', 'k', "'", ',', 'J', 'H', 'N', 'A', 'd', 'E', 'a', ' ', '$', '1'}
83


In [4]:
v2i = {c:i for i,c in enumerate(vocab)}
print(v2i)

{')': 0, 'K': 1, 'T': 2, '_': 3, 'L': 4, 'B': 5, '`': 6, 'o': 7, 'X': 8, 'l': 9, 'P': 10, '5': 11, '(': 12, ';': 13, 'v': 14, '8': 15, 'n': 16, 'C': 17, 'h': 18, 'e': 19, '0': 20, 'x': 21, 'Y': 22, ':': 23, '3': 24, '4': 25, 'V': 26, '"': 27, '*': 28, 'F': 29, 'j': 30, '\n': 31, '!': 32, 'R': 33, 'Q': 34, 'S': 35, '/': 36, '2': 37, '%': 38, '?': 39, 'm': 40, '.': 41, 'y': 42, 'f': 43, 'q': 44, 'G': 45, 'Z': 46, '6': 47, 'i': 48, 'D': 49, 'u': 50, 'I': 51, 'z': 52, 'p': 53, 'r': 54, '-': 55, 'g': 56, 's': 57, 'b': 58, 'W': 59, '7': 60, 'U': 61, 'O': 62, '9': 63, '@': 64, '&': 65, 't': 66, 'w': 67, 'c': 68, 'M': 69, 'k': 70, "'": 71, ',': 72, 'J': 73, 'H': 74, 'N': 75, 'A': 76, 'd': 77, 'E': 78, 'a': 79, ' ': 80, '$': 81, '1': 82}


In [5]:
i2v = dict(enumerate(vocab))
print(i2v)

{0: ')', 1: 'K', 2: 'T', 3: '_', 4: 'L', 5: 'B', 6: '`', 7: 'o', 8: 'X', 9: 'l', 10: 'P', 11: '5', 12: '(', 13: ';', 14: 'v', 15: '8', 16: 'n', 17: 'C', 18: 'h', 19: 'e', 20: '0', 21: 'x', 22: 'Y', 23: ':', 24: '3', 25: '4', 26: 'V', 27: '"', 28: '*', 29: 'F', 30: 'j', 31: '\n', 32: '!', 33: 'R', 34: 'Q', 35: 'S', 36: '/', 37: '2', 38: '%', 39: '?', 40: 'm', 41: '.', 42: 'y', 43: 'f', 44: 'q', 45: 'G', 46: 'Z', 47: '6', 48: 'i', 49: 'D', 50: 'u', 51: 'I', 52: 'z', 53: 'p', 54: 'r', 55: '-', 56: 'g', 57: 's', 58: 'b', 59: 'W', 60: '7', 61: 'U', 62: 'O', 63: '9', 64: '@', 65: '&', 66: 't', 67: 'w', 68: 'c', 69: 'M', 70: 'k', 71: "'", 72: ',', 73: 'J', 74: 'H', 75: 'N', 76: 'A', 77: 'd', 78: 'E', 79: 'a', 80: ' ', 81: '$', 82: '1'}


In [8]:
## encoding the whole book
encoded_text = np.array([v2i[c] for c in text], dtype=np.int32)
print(encoded_text)

[17 18 79 ..., 57 41 31]


In [9]:
def get_batches(arr, n_seqs, n_steps):
    batch_size = n_seqs*n_steps #tot # of chars in each batch
    n_batches = len(arr)//batch_size
    
    ## round the batches
    arr = arr[:batch_size*n_batches]
    arr = arr.reshape(n_seqs,-1)
    
    for n in range(0, n_seqs, n_steps):
        x = arr[:,n:n+n_steps]
        y= np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x,y

In [10]:
tmp = np.array([1,2,3,4,5,6])
tmp.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
batches = get_batches(encoded_text, 10, 50)
type(batches)

generator

In [12]:
x, y = next(batches)

In [14]:
x[:10, :10]

array([[17, 18, 79, 53, 66, 19, 54, 80, 82, 31],
       [80, 79, 40, 80, 16,  7, 66, 80, 56,  7],
       [14, 48, 16, 41, 31, 31, 27, 22, 19, 57],
       [16, 80, 77, 50, 54, 48, 16, 56, 80, 18],
       [80, 48, 66, 80, 48, 57, 72, 80, 57, 48],
       [80, 51, 66, 80, 67, 79, 57, 31,  7, 16],
       [18, 19, 16, 80, 68,  7, 40, 19, 80, 43],
       [13, 80, 58, 50, 66, 80, 16,  7, 67, 80],
       [66, 80, 48, 57, 16, 71, 66, 41, 80,  2],
       [80, 57, 79, 48, 77, 80, 66,  7, 80, 18]])

In [34]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[ 3 47 32 31 15 23  9 20 46 76]
 [20 32 64 20 81 43 15 20 69 43]
 [29 18 81 16 76 76 33 30 23 57]
 [81 20 65 53  9 18 81 69 20 47]
 [20 18 15 20 18 57 21 20 57 18]
 [20 51 15 20 28 32 57 76 43 81]
 [47 23 81 20 70 43 64 23 20 48]
 [78 20 44 53 15 20 81 43 28 20]
 [15 20 18 57 81 66 15 16 20 74]
 [20 57 32 18 65 20 15 43 20 47]]

y
 [[47 32 31 15 23  9 20 46 76 76]
 [32 64 20 81 43 15 20 69 43 18]
 [18 81 16 76 76 33 30 23 57 21]
 [20 65 53  9 18 81 69 20 47 18]
 [18 15 20 18 57 21 20 57 18  9]
 [51 15 20 28 32 57 76 43 81 80]
 [23 81 20 70 43 64 23 20 48 43]
 [20 44 53 15 20 81 43 28 20 57]
 [20 18 57 81 66 15 16 20 74 47]
 [57 32 18 65 20 15 43 20 47 23]]


In [37]:
def build_inputs(n_seqs, num_steps):
    inputs = tf.placeholder(tf.int32, [n_seqs, num_steps], name='input')
    target = tf.placeholder(tf.int32, [n_seqs, num_steps], name='target')
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, target, keep_prob

In [ ]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    
    def build_cell(lstm_size, keep_prob):
        # Use a basic LSTM cell
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        
        # Add dropout to the cell
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
    
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

In [ ]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        x: Input tensor
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # That is, the shape should be batch_size*num_steps rows by lstm_size columns
    seq_output = tf.concat(lstm_output, axis=1)
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits