In [3]:
import tensorflow as tf
import numpy as np

from collections import namedtuple
import time

In [4]:
## converting chars to integers
with open('anna.txt','r') as f:
    text= f.read()

vocab = set(text)

In [21]:
print(vocab)
print(len(vocab))
## we get all the unique terms used

{'7', '9', 'x', 'C', 'Q', 'X', '&', '2', 'S', 'r', 'D', '*', 'V', '?', 'M', 't', '.', ':', 'i', '%', ' ', ',', 'z', 'e', 'L', '$', 'H', 'W', 'w', 'v', 'Y', 'p', 'a', '"', 'N', '8', '/', 'E', 'y', 'j', '(', 'U', 'J', 'o', 'b', '`', '1', 'h', 'f', 'F', '-', 'I', 'R', 'u', 'B', '4', 'A', 's', '3', '!', 'G', 'q', '@', 'K', 'm', 'd', "'", 'O', '_', 'g', 'c', ')', '5', '0', 'T', 'Z', '\n', '6', ';', 'P', 'l', 'n', 'k'}
83


In [16]:
v2i = {c:i for i,c in enumerate(vocab)}
print(v2i)

{'7': 0, '9': 1, 'x': 2, 'C': 3, 'Q': 4, 'X': 5, '&': 6, '2': 7, 'S': 8, 'r': 9, 'D': 10, '*': 11, 'V': 12, '?': 13, 'M': 14, 't': 15, '.': 16, ':': 17, 'i': 18, '%': 19, ' ': 20, ',': 21, 'z': 22, 'e': 23, 'L': 24, '$': 25, 'H': 26, 'W': 27, 'w': 28, 'v': 29, 'Y': 30, 'p': 31, 'a': 32, '"': 33, 'N': 34, '8': 35, '/': 36, 'E': 37, 'y': 38, 'j': 39, '(': 40, 'U': 41, 'J': 42, 'o': 43, 'b': 44, '`': 45, '1': 46, 'h': 47, 'f': 48, 'F': 49, '-': 50, 'I': 51, 'R': 52, 'u': 53, 'B': 54, '4': 55, 'A': 56, 's': 57, '3': 58, '!': 59, 'G': 60, 'q': 61, '@': 62, 'K': 63, 'm': 64, 'd': 65, "'": 66, 'O': 67, '_': 68, 'g': 69, 'c': 70, ')': 71, '5': 72, '0': 73, 'T': 74, 'Z': 75, '\n': 76, '6': 77, ';': 78, 'P': 79, 'l': 80, 'n': 81, 'k': 82}


In [17]:
i2v = dict(enumerate(vocab))
print(i2v)

{0: '7', 1: '9', 2: 'x', 3: 'C', 4: 'Q', 5: 'X', 6: '&', 7: '2', 8: 'S', 9: 'r', 10: 'D', 11: '*', 12: 'V', 13: '?', 14: 'M', 15: 't', 16: '.', 17: ':', 18: 'i', 19: '%', 20: ' ', 21: ',', 22: 'z', 23: 'e', 24: 'L', 25: '$', 26: 'H', 27: 'W', 28: 'w', 29: 'v', 30: 'Y', 31: 'p', 32: 'a', 33: '"', 34: 'N', 35: '8', 36: '/', 37: 'E', 38: 'y', 39: 'j', 40: '(', 41: 'U', 42: 'J', 43: 'o', 44: 'b', 45: '`', 46: '1', 47: 'h', 48: 'f', 49: 'F', 50: '-', 51: 'I', 52: 'R', 53: 'u', 54: 'B', 55: '4', 56: 'A', 57: 's', 58: '3', 59: '!', 60: 'G', 61: 'q', 62: '@', 63: 'K', 64: 'm', 65: 'd', 66: "'", 67: 'O', 68: '_', 69: 'g', 70: 'c', 71: ')', 72: '5', 73: '0', 74: 'T', 75: 'Z', 76: '\n', 77: '6', 78: ';', 79: 'P', 80: 'l', 81: 'n', 82: 'k'}


In [20]:
## encoding the whole book
encoded_text = np.array([v2i[c] for c in text], dtype=np.int32)
print(encoded_text)

[ 3 47 32 ..., 57 16 76]


In [29]:
def get_batches(arr, n_seqs, n_steps):
    batch_size = n_seqs*n_steps
    n_batches = len(arr)//batch_size
    
    ## round the batches
    arr = arr[:batch_size*n_batches]
    arr = arr.reshape(n_seqs,-1)
    
    for n in range(0, n_seqs, n_steps):
        x = arr[:,n:n+n_steps]
        y= np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x,y

In [30]:
batches = get_batches(encoded_text, 10, 50)
type(batches)

generator

In [31]:
x, y = next(batches)

In [34]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[ 3 47 32 31 15 23  9 20 46 76]
 [20 32 64 20 81 43 15 20 69 43]
 [29 18 81 16 76 76 33 30 23 57]
 [81 20 65 53  9 18 81 69 20 47]
 [20 18 15 20 18 57 21 20 57 18]
 [20 51 15 20 28 32 57 76 43 81]
 [47 23 81 20 70 43 64 23 20 48]
 [78 20 44 53 15 20 81 43 28 20]
 [15 20 18 57 81 66 15 16 20 74]
 [20 57 32 18 65 20 15 43 20 47]]

y
 [[47 32 31 15 23  9 20 46 76 76]
 [32 64 20 81 43 15 20 69 43 18]
 [18 81 16 76 76 33 30 23 57 21]
 [20 65 53  9 18 81 69 20 47 18]
 [18 15 20 18 57 21 20 57 18  9]
 [51 15 20 28 32 57 76 43 81 80]
 [23 81 20 70 43 64 23 20 48 43]
 [20 44 53 15 20 81 43 28 20 57]
 [20 18 57 81 66 15 16 20 74 47]
 [57 32 18 65 20 15 43 20 47 23]]


In [ ]:
def build_inputs(batch_size, num_steps):
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps])